export const ConditionsIcons = {
  ClearSky: require('../assets/images/clear-sky.png'),
  FewClouds: require('../assets/images/few-clouds.png'),
  ScatteredClouds: require('../assets/images/few-clouds.png'),
  BrokenClouds: require('../assets/images/broken-clouds.png'),
  ShowerRain: require('../assets/images/shower-rain.png'),
  Rain: require('../assets/images/shower-rain.png'),
  Thunderstorm: require('../assets/images/thunderstorm.png'),
  Snow: require('../assets/images/snow.png'),
  Mist: require('../assets/images/mist.png'),
};

export const WeatherConditionsIcons = {
  200: ConditionsIcons.Thunderstorm,
  201: ConditionsIcons.Thunderstorm,
  202: ConditionsIcons.Thunderstorm,
  210: ConditionsIcons.Thunderstorm,
  211: ConditionsIcons.Thunderstorm,
  212: ConditionsIcons.Thunderstorm,
  221: ConditionsIcons.Thunderstorm,
  230: ConditionsIcons.Thunderstorm,
  231: ConditionsIcons.Thunderstorm,
  232: ConditionsIcons.Thunderstorm,

  300: ConditionsIcons.ShowerRain,
  301: ConditionsIcons.ShowerRain,
  302: ConditionsIcons.ShowerRain,
  310: ConditionsIcons.ShowerRain,
  311: ConditionsIcons.ShowerRain,
  312: ConditionsIcons.ShowerRain,
  313: ConditionsIcons.ShowerRain,
  314: ConditionsIcons.ShowerRain,
  321: ConditionsIcons.ShowerRain,

  500: ConditionsIcons.Rain,
  501: ConditionsIcons.Rain,
  502: ConditionsIcons.Rain,
  503: ConditionsIcons.Rain,
  504: ConditionsIcons.Rain,
  511: ConditionsIcons.Snow,
  520: ConditionsIcons.ShowerRain,
  521: ConditionsIcons.ShowerRain,
  522: ConditionsIcons.ShowerRain,
  531: ConditionsIcons.ShowerRain,

  600: ConditionsIcons.Snow,
  601: ConditionsIcons.Snow,
  602: ConditionsIcons.Snow,
  611: ConditionsIcons.Snow,
  612: ConditionsIcons.Snow,
  613: ConditionsIcons.Snow,
  615: ConditionsIcons.Snow,
  616: ConditionsIcons.Snow,
  620: ConditionsIcons.Snow,
  621: ConditionsIcons.Snow,
  622: ConditionsIcons.Snow,

  700: ConditionsIcons.Mist,
  711: ConditionsIcons.Mist,
  721: ConditionsIcons.Mist,
  731: ConditionsIcons.Mist,
  741: ConditionsIcons.Mist,
  751: ConditionsIcons.Mist,
  761: ConditionsIcons.Mist,
  762: ConditionsIcons.Mist,
  771: ConditionsIcons.Mist,
  781: ConditionsIcons.Mist,

  800: ConditionsIcons.ClearSky,
  801: ConditionsIcons.FewClouds,
  802: ConditionsIcons.BrokenClouds,
  803: ConditionsIcons.BrokenClouds,
  804: ConditionsIcons.BrokenClouds,
};
